# Generated by Django 2.2.2 on 2020-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyad')),
                ('mail', models.CharField(max_length=30, verbose_name='Mail')),
                ('date', models.DateField()),
                ('phone_number', models.CharField(max_length=12, verbose_name='Tel')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmet', models.CharField(max_length=30, verbose_name='Hizmet')),
                ('price', models.CharField(max_length=30, verbose_name='Fiyat')),
            ],
        ),
    ]
