# Generated by Django 2.2.2 on 2020-08-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayfun_gurun_hair_design_studio', '0002_auto_20200825_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Tel')),
                ('mail', models.CharField(max_length=30, verbose_name='Mail')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyad')),
            ],
        ),
    ]
