# Generated by Django 2.2.2 on 2020-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayfun_gurun_hair_design_studio', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail_sended',
            field=models.CharField(max_length=30, null=True, verbose_name='Mail Yollandı'),
        ),
    ]
